apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-pv
spec:
  storageClassName: "file-storage"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/file/data
    type: DirectoryOrCreate
